# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry
application:
  track: stable
  tier: web
service:
  enabled: true
  name: web
  type: ClusterIP
  url: http://my.host.com/
  externalPort: 80
  internalPort: 80
postgresql:
  enabled: true
resources:
  limits:
    cpu: 2
    memory: 8Gi
  requests:
    cpu: 10m
    memory: 32Mi
